import os

SPOTIFY_API_CONFIG = {
    'SPOTIFY_CLIENT_ID': os.environ.get('SPOTIFY_CLIENT_ID'),
    'SPOTIFY_CLIENT_SECRET': os.environ.get('SPOTIFY_CLIENT_SECRET'),
    'SPOTIFY_CALLBACK_URL': os.environ.get('SPOTIFY_CALLBACK_URL'),
}

MONGODB_CONFIG = {
    'USERNAME': os.environ.get('MONGO_USERNAME'),
    'PASSWORD': os.environ.get('MONGO_PASSWORD')
}
MONGODB_CONNECTION_STRING_FORMAT = os.environ.get('MONGODB_CONNECTION_STRING_FORMAT')

MONGODB_CONFIG['CONNECTION_STRING'] = MONGODB_CONNECTION_STRING_FORMAT.format(**MONGODB_CONFIG)
